name: releaser

on:
  push:
    tags:
      - "*"

jobs:
  releaser:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        shell: pwsh
        run: |
          $TAG = git describe --tags "$(git rev-list --tags --max-count=1)"
          $COMMIT = git rev-parse --short HEAD
          go build -installsuffix 'static' -ldflags="-X main.version=$TAG -X main.commit=$COMMIT" -o ../build/galactus.exe .

      - name: Compress build files to zip
        shell: pwsh
        run: Compress-Archive -Path ../build/* -DestinationPath ../galactus.zip

      - name: Create hashes.txt
        shell: pwsh
        run: |
          Get-ChildItem ..\build\ -Recurse -File -Force -ea SilentlyContinue -ev errs | Get-FileHash -Algorithm SHA256 | Select-Object -Property Hash, @{Label="Path"; Expression={((Resolve-Path -Relative $_.Path) -replace '..\\build\\','') -replace '\\','/'}} | ForEach-Object { $_.Hash + " " + $_.Path } | Out-File -FilePath ..\hashes.txt

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - name: Upload asset
        id: upload-release-asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ../galactus.zip
            ../hashes.txt
